version: '3.4'

networks:
  internal:
    name: internal
    driver: bridge

services:
  db-postgres:
    image: postgres:15.2-alpine3.17
    container_name: db-postgres
    env_file: .env.dev
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${PGSQL_NAME}
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    networks:
      - internal

  backend:
    image: node:18.16.0-alpine3.17
    container_name: backend
    working_dir: /usr/src/app
    env_file: .env.dev
    restart: always
    depends_on:
      - db-postgres
    command: sh -c "npm i && npm run build && npm run start:dev"
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - internal
