version: '3.7'

networks:
  internal:
    name: internal
    driver: bridge

services:
  db-postgres:
    image: postgres:15-alpine3.17
    container_name: db-postgres
    env_file: .env
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${PGSQL_NAME}
      POSTGRES_USER: ${PGSQL_USER}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
    volumes:
      - ./database/postgres:/var/lib/postgresql/data
    networks:
      - internal
