name: CI/CD Pipeline

on:
  pull_request:
    types:
      - closed
    branches:
      - 'production'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  CI-CD:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: 📂 Checkout repository
        uses: actions/checkout@v3

      - name: 🐋 Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 📑 Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=production

      - name: 🛠️ Build and push Docker image to ghcr
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          target: production
          push: true
          tags: |
            ghcr.io/projetointegradorstudy/condo-management-backend:v1.0.${{github.run_number}}
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
