name: Unit Test

on: ['pull_request']

jobs:
  Unit_Test:
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checking repository
        uses: actions/checkout@v3

      - name: 🔧 Installing Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Installing the dependencies from package.json
        run: npm ci

      - name: 💥 Running unit tests
        run: npm test
